### ISSUE TITLE
Make the sandwich order menu look nicer

### ISSUE THREAD

**Issue by vvanpomeren** [NitraatPlagiaat/broodcode#10]
Change the console output of the sandwich order menu.
It will look nicer when sharing and posting it :)

**I would suggest something from this:**

__
Freshly topped sandwiches
__

Jong belegen kaas: wit=500 grain=501 foca=502 spelt=503 g-vrij=600
Kruidenroomkaas: wit=601 grain=602 foca=603 spelt=604 g-vrij=700
Falafel : wit=630 grain=631 foca=632 spelt=633 g-vrij=730
Oude Kaas: wit=650 grain=651 foca=652 spelt=653 g-vrij=750
Chengdu Chicken: wit=654 grain=655 foca=656 spelt=657 g-vrij=751
etc...

**To for example this:**

## Freshly topped sandwiches

```markdown
|Sandwich          |White|Grain|Focaccia|Spelt|Gluten-Free|
|------------------|-----|-----|--------|-----|-----------|
|Jong belegen kaas |500  |501  |502     |503  |600        |
|Kruidenroomkaas   |601  |602  |603     |604  |700        |
|Falafel           |630  |631  |632     |633  |730        |
|Oude Kaas         |650  |651  |652     |653  |750        |
|Chengdu Chicken   |654  |655  |656     |657  |751        |
etc...
```

**Comment by vvanpomeren** [comment]
I *could* work on this if you dont mind

**Comment by NitraatPlagiaat** [comment]
Thank you Vincent. I don't mind if you want to work on that.

What i want to ask you is after you clone the repository is that you work from the 'dev' branch. So that you can make another branch based on the dev branch. I'm looking forward to your pull request when you're done.

Also, if you run into any issues regarding this repository, let me know.
